package com.damian.apexedu.util;

public enum Buttons {
    CCS,HND,UNDERGRAD,LECTURERS,ATTENDANCE,FINANCE,LECBUTTON,STUDENTBUTTON,HOMESCREENLOGIN,HOMEBUTTON,CCSATTENDANCE,HNDATTENDANCE,UNDERGRADATTENDANCE
}
