package com.damian.apexedu.util;

public enum Routes {
    AdminDashBoard,CCS,HND,UNDERGRAD,LECTURERS,ATTENDANCE,FINANCE,LECTURERLOGIN,STUDENTLOGIN,STUDENTSIGNUP,HOMESCREEN,LECTURERDASHBOARD,CCSANNOUNCEMENTS,HNDANNOUNCEMENTS,UNDERGRADANNOUNCEMENTS,STUDENTDASHBOARD,ATTENDANCEVIEWER,VIEWANNOUNCEMENTS,WEB,FEES,ATTENDANCEMANAGER,PIECHART,DETAILEDATTENDANCEREPORT,BARCHART
}
