package com.damian.apexedu.service;

public enum ServiceTypes {
    CCS_DETAILS,CCS_FEES,CCS_CREDENTIALS,HND_DETAILS,HND_FEES,HND_CREDENTIALS,UNDERGRAD,UNDERGRAD_CREDENTIALS,UNDERGRAD_FEES,LECTURER_DETAILS,LECTURER_CREDENTIALS,CCS_ATTENDANCE,HND_ATTENDANCE,UNDERGRAD_ATTENDANCE,CCS_ANNOUNCEMENTS,HND_ANNOUNCEMENTS,UNDERGRAD_ANNOUNCEMENTS


}
